<a href="https://colab.research.google.com/github/Mayurrathod1/Data-Analysis-Project-Python-SQL-/blob/main/data_analytics_project_orders_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import libraries
!kaggle.api.authenticate()

# Install the Kaggle library
!pip install kaggle

# Download the dataset
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

/bin/bash: -c: line 2: syntax error: unexpected end of file
Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.6.17)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2024.8.30)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.66.5)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.2.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.10)
Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to /content
  0% 0.00/200k [00:00<?, ?B/s]
100% 200k/200k [00:00<00:00, 41.8MB/s]

In [ ]:
#extract file from zip file
import zipfile
zip_ref = zipfile.ZipFile('/content/orders.csv.zip')
zip_ref.extractall() # extract file to dir
zip_ref.close() # close file

In [ ]:
import pandas as pd
df = pd.read_csv('/content/orders.csv')
df.head(10)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3

In [ ]:
import pandas as pd
df = pd.read_csv('/content/orders.csv')
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [ ]:
#read data from the file and handle null values
import pandas as pd
df = pd.read_csv('orders.csv',na_values=['Not Available','unknown'])
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [ ]:
#rename columns names. make them lower case and replace space with underscore
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [ ]:
#derive new columns discount, sale price and profit
df['discount']=df['list_price']*df['discount_percent']*.01
df['sale_price']= df['list_price']-df['discount']
df['profit']=df['sale_price']-df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [ ]:
df.dtypes

order_id              int64
order_date           object
ship_mode            object
segment              object
country              object
city                 object
state                object
postal_code           int64
region               object
category             object
sub_category         object
product_id           object
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount            float64
sale_price          float64
profit              float64
dtype: object

In [ ]:
#convert order date from object data type to datetime
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")

In [ ]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [ ]:
# Drop columns, ignoring errors if they don't exist
df.drop(columns=['list_price', 'cost_price', 'discount_percent'], inplace=True, errors='ignore')
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0

In [ ]:
import sqlite3

# Connect to the database
conn = sqlite3.connect('df_orders')

#load the data into sql server using append option
df.to_sql('df_orders', con=conn , index=False, if_exists = 'replace')
cursor = conn.cursor()

# Execute the SQL query to select all data from the df_orders table
cursor.execute('''SELECT * FROM df_orders
LIMIT 10;''')

# Fetch all rows from the result set
rows = cursor.fetchall()

# Print the results
for row in rows:
    print(row)

# Close the connection
conn.close()

(1, '2023-03-01 00:00:00', 'Second Class', 'Consumer', 'United States', 'Henderson', 'Kentucky', 42420, 'South', 'Furniture', 'Bookcases', 'FUR-BO-10001798', 2, 5.2, 254.8, 14.800000000000011)
(2, '2023-08-15 00:00:00', 'Second Class', 'Consumer', 'United States', 'Henderson', 'Kentucky', 42420, 'South', 'Furniture', 'Chairs', 'FUR-CH-10000454', 3, 21.900000000000002, 708.1, 108.10000000000002)
(3, '2023-01-10 00:00:00', 'Second Class', 'Corporate', 'United States', 'Los Angeles', 'California', 90036, 'West', 'Office Supplies', 'Labels', 'OFF-LA-10000240', 2, 0.5, 9.5, -0.5)
(4, '2022-06-18 00:00:00', 'Standard Class', 'Consumer', 'United States', 'Fort Lauderdale', 'Florida', 33311, 'South', 'Furniture', 'Tables', 'FUR-TA-10000577', 5, 19.2, 940.8, 160.79999999999995)
(5, '2022-07-13 00:00:00', 'Standard Class', 'Consumer', 'United States', 'Fort Lauderdale', 'Florida', 33311, 'South', 'Office Supplies', 'Storage', 'OFF-ST-10000760', 2, 1.0, 19.0, -1.0)
(6, '2022-03-13 00:00:00', None, 'Consumer', 'United States', 'Los Angeles', 'California', 90032, 'West', 'Furniture', 'Furnishings', 'FUR-FU-10001487', 7, 1.5, 48.5, -1.5)
(7, '2022-12-28 00:00:00', 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', 90032, 'West', 'Office Supplies', 'Art', 'OFF-AR-10002833', 4, 0.3, 9.7, -0.3000000000000007)
(8, '2022-01-25 00:00:00', 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', 90032, 'West', 'Technology', 'Phones', 'TEC-PH-10002275', 6, 45.5, 864.5, 4.5)
(9, '2023-03-23 00:00:00', None, 'Consumer', 'United States', 'Los Angeles', 'California', 90032, 'West', 'Office Supplies', 'Binders', 'OFF-BI-10003910', 3, 0.4, 19.6, -0.3999999999999986)
(10, '2023-05-16 00:00:00', 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', 90032, 'West', 'Office Supplies', 'Appliances', 'OFF-AP-10002892', 5, 3.3000000000000003, 106.7, 16.700000000000003)

In [ ]:
# Connect to your SQLite3 database
conn = sqlite3.connect('df_orders')
cursor = conn.cursor()

# Execute the SQL query
cursor.execute("""
SELECT product_id, SUM(sale_price) AS sales
FROM df_orders
GROUP BY product_id
ORDER BY sales DESC
LIMIT 10;
""")

# Fetch the results
results = cursor.fetchall()

# Print the results
for row in results:
    print(row)

# Close the connection
conn.close()

('TEC-CO-10004722', 119028.0)
('OFF-BI-10003527', 53050.600000000006)
('TEC-MA-10002412', 43468.8)
('FUR-CH-10002024', 42192.4)
('OFF-BI-10001359', 38180.4)
('OFF-BI-10000545', 36498.0)
('TEC-CO-10001449', 36302.4)
('TEC-MA-10001127', 35812.8)
('OFF-BI-10004995', 34709.6)
('OFF-SU-10000151', 32651.6)

In [ ]:
# Connect to your SQLite3 database
conn = sqlite3.connect('df_orders')
cursor = conn.cursor()

# Execute the SQL query
cursor.execute('''
WITH cte AS (
    SELECT region, product_id, SUM(sale_price) AS sales
    FROM df_orders
    GROUP BY region, product_id
)
SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY region ORDER BY sales DESC) AS rn
    FROM cte
) A
WHERE rn <= 5;
''')

# Fetch the results
results = cursor.fetchall()

# Print the results
for row in results:
    print(row)

# Close the connection
conn.close()

('Central', 'TEC-CO-10004722', 33950.0, 1)
('Central', 'TEC-MA-10000822', 27540.0, 2)
('Central', 'OFF-BI-10001120', 22113.0, 3)
('Central', 'OFF-BI-10000545', 20265.4, 4)
('Central', 'OFF-BI-10004995', 16832.2, 5)
('East', 'TEC-CO-10004722', 58198.0, 1)
('East', 'TEC-MA-10001047', 27534.0, 2)
('East', 'FUR-BO-10004834', 22548.2, 3)
('East', 'OFF-BI-10001359', 16927.199999999997, 4)
('East', 'TEC-CO-10001449', 16632.0, 5)
('South', 'TEC-MA-10002412', 43468.8, 1)
('South', 'TEC-MA-10001127', 22232.8, 2)
('South', 'OFF-BI-10001359', 16106.4, 3)
('South', 'TEC-MA-10004125', 15680.0, 4)
('South', 'OFF-BI-10003527', 14782.8, 5)
('West', 'TEC-CO-10004722', 26880.0, 1)
('West', 'OFF-SU-10000151', 25184.6, 2)
('West', 'FUR-CH-10001215', 19208.0, 3)
('West', 'OFF-BI-10003527', 15609.599999999999, 4)
('West', 'TEC-AC-10003832', 15445.400000000003, 5)

In [ ]:
# Connect to your SQLite3 database
conn = sqlite3.connect('df_orders')
cursor = conn.cursor()

# Execute the SQL query, using strftime to extract year and month
cursor.execute('''
WITH cte AS (
    SELECT STRFTIME('%Y', order_date) AS order_year,
           STRFTIME('%m', order_date) AS order_month,
           SUM(sale_price) AS sales
    FROM df_orders
    GROUP BY STRFTIME('%Y', order_date), STRFTIME('%m', order_date)
)
SELECT order_month,
       SUM(CASE WHEN order_year = '2022' THEN sales ELSE 0 END) AS sales_2022,
       SUM(CASE WHEN order_year = '2023' THEN sales ELSE 0 END) AS sales_2023
FROM cte
GROUP BY order_month
ORDER BY order_month;
''')

# Fetch the results
results = cursor.fetchall()

# Print the results
for row in results:
    print(row)

# Close the connection
conn.close()

('01', 189425.0000000002, 177265.20000000024)
('02', 180181.9999999999, 256248.4000000002)
('03', 160211.99999999994, 165024.6000000003)
('04', 190903.19999999995, 223137.20000000036)
('05', 158896.6000000001, 172895.80000000022)
('06', 188341.00000000017, 137953.00000000006)
('07', 157304.4000000002, 181127.60000000015)
('08', 209615.99999999983, 175467.19999999992)
('09', 158284.4000000001, 153317.2000000001)
('10', 237825.4000000002, 242122.9999999997)
('11', 168450.60000000024, 150865.60000000015)
('12', 191739.80000000013, 205112.20000000022)

In [ ]:
# Connect to your SQLite3 database
conn = sqlite3.connect('df_orders')
cursor = conn.cursor()

# Execute the SQL query
cursor.execute('''
WITH cte AS (
    SELECT category,
           strftime('%Y%m', order_date) AS order_year_month,
           SUM(sale_price) AS sales
    FROM df_orders
    GROUP BY category, strftime('%Y%m', order_date)
)
SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY sales DESC) AS rn
    FROM cte
) A
WHERE rn = 1;
''')

# Fetch the results
results = cursor.fetchall()

# Print the results
for row in results:
    print(row)

# Close the connection
conn.close()

('Furniture', '202210', 85777.80000000002, 1)
('Office Supplies', '202302', 88237.00000000007, 1)
('Technology', '202310', 106000.19999999997, 1)

In [ ]:
# Connect to your SQLite3 database
conn = sqlite3.connect('df_orders')
cursor = conn.cursor()

# Execute the SQL query
cursor.execute('''
WITH cte AS (
    SELECT sub_category, STRFTIME('%Y', order_date) AS order_year, SUM(sale_price) AS sales
    FROM df_orders
    GROUP BY sub_category, STRFTIME('%Y', order_date)
),
cte2 AS (
    SELECT sub_category,
           SUM(CASE WHEN order_year = '2022' THEN sales ELSE 0 END) AS sales_2022,
           SUM(CASE WHEN order_year = '2023' THEN sales ELSE 0 END) AS sales_2023
    FROM cte
    GROUP BY sub_category
)
SELECT sub_category, (sales_2023 - sales_2022) AS growth
FROM cte2
ORDER BY growth DESC
LIMIT 1;
''')

# Fetch the result
result = cursor.fetchone()

# Print the result
print(result)

# Close the connection
conn.close()

('Machines', 70910.60000000003)